name: jupyter-web-application
channels:
  - fastai
  - conda-forge
dependencies:
  - aiofiles=22.1.0
  - aiosqlite=0.19.0
  - anyio=3.7.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - astunparse=1.6.3
  - attrs=23.1.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - bleach=6.0.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - colorama=0.4.6
  - comm=0.1.3
  - contourpy=1.1.0
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.1.1
  - execnb=0.1.5
  - executing=1.2.0
  - fastcore=1.5.28
  - flit-core=3.9.0
  - fonttools=4.40.0
  - freetype=2.12.1
  - gettext=0.21.1
  - ghapi=1.0.4
  - glib=2.76.3
  - glib-tools=2.76.3
  - gst-plugins-base=1.22.4
  - gstreamer=1.22.4
  - icu=72.1
  - idna=3.4
  - importlib-metadata=6.7.0
  - importlib-resources=5.12.0
  - importlib_metadata=6.7.0
  - importlib_resources=5.12.0
  - intel-openmp=2023.1.0
  - ipykernel=6.23.3
  - ipython=8.12.2
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.6
  - jedi=0.18.2
  - jinja2=3.1.2
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.1
  - jupyter_console=6.6.3
  - jupyter_core=5.3.1
  - jupyter_events=0.6.3
  - jupyter_server=1.23.6
  - jupyter_server_fileid=0.9.0
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.5
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.23.0
  - jupyterlab_widgets=3.0.7
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.15
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=16.0.6
  - libclang13=16.0.6
  - libdeflate=1.18
  - libffi=3.4.2
  - libglib=2.76.3
  - libhwloc=2.9.1
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libogg=1.3.4
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libtiff=4.5.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.1
  - libxcb=1.15
  - libxml2=2.11.4
  - libzlib=1.2.13
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.3
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mistune=3.0.0
  - mkl=2022.1.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nbclassic=1.0.0
  - nbclient=0.7.4
  - nbconvert=7.6.0
  - nbconvert-core=7.6.0
  - nbconvert-pandoc=7.6.0
  - nbdev=2.3.12
  - nbformat=5.9.0
  - nest-asyncio=1.5.6
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - numpy=1.24.4
  - openjpeg=2.5.0
  - openssl=3.1.1
  - packaging=23.1
  - pandas=2.0.3
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.3
  - pcre2=10.40
  - pickleshare=0.7.5
  - pillow=9.5.0
  - pip=23.1.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.8.0
  - ply=3.11
  - pooch=1.7.0
  - prometheus_client=0.17.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.5
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyparsing=3.1.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.8.17
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.17.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.8
  - pytz=2023.3
  - pywin32=304
  - pywinpty=2.0.10
  - pyyaml=6.0
  - pyzmq=25.1.0
  - qt-main=5.15.8
  - qtconsole=5.4.3
  - qtconsole-base=5.4.3
  - qtpy=2.3.1
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - scipy=1.10.1
  - send2trash=1.8.2
  - setuptools=68.0.0
  - sip=6.7.9
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - stack_data=0.6.2
  - statsmodels=0.14.0
  - tbb=2021.9.0
  - terminado=0.17.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.3.2
  - traitlets=5.9.0
  - typing-extensions=4.7.0
  - typing_extensions=4.7.0
  - ucrt=10.0.22621.0
  - unicodedata2=15.0.0
  - urllib3=2.0.3
  - vc=14.3
  - vc14_runtime=14.36.32532
  - voila=0.4.1
  - vs2015_runtime=14.36.32532
  - watchdog=3.0.0
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.6.1
  - websockets=11.0.3
  - wheel=0.40.0
  - widgetsnbextension=4.0.7
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - y-py=0.5.9
  - yaml=0.2.5
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zipp=3.15.0
  - zstd=1.5.2