on:
  push:

env:
  ENVIRONMENT_NAME: jupyter-web-application

defaults:
  run:
    shell: bash -l {0}

jobs:
  conda:
    name: conda env (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - windows-2022
          - windows-2019
          - ubuntu-22.04
          - ubuntu-20.04
          - macos-13
          - macos-12
          - macos-11
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: latest
      - name: Install from original env file
        run: |
          conda env create -f environment.yml
      - name: Save resolved environment with pinned dependencies
        run: |
          conda env export -n "$ENVIRONMENT_NAME" --no-builds > environment.yml
      - uses: actions/upload-artifact@v3
        with:
          path: environment.yml
          name: environment-${{ matrix.runner }}
